name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    
    steps:
      - name: Set up JDK 17 (Requerido por SonarScanner)
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
      # PASO CLAVE: Instala el paquete de escritorio para evitar el error NETSDK1127 
      - name: Install .NET 6.0 Windows Desktop Runtime
        shell: powershell
        run: |
          # Asegura que el runtime de escritorio esté disponible para la solución de WinForms/WPF
          dotnet workload install Microsoft.NET.Sdk.WindowsDesktop --sdk-version 6.0.422

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 es crucial para análisis de "código nuevo" y PRs
          fetch-depth: 0

      # Los pasos de Cacheo son correctos y se mantienen
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\.sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarQube Cloud scanner
        shell: powershell
        run: dotnet tool install dotnet-sonarscanner --global --version 6.0.0 # Usamos --global para simplificar

      # --- PASOS DE ANÁLISIS Y TESTS CORREGIDOS ---
      - name: Run analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          $scanner = "dotnet-sonarscanner"
          $solutionPath = "ReporteGasto\ReporteGasto.sln"
          $projectName = "Rubidescalz_reportegasto"
          $orgName = "rubidescalz"
          
          # 1. INICIA el análisis y activa la recopilación de Cobertura
          Write-Host "1. Inicia el análisis de SonarScanner..."
          & $scanner begin `
            /k:"$projectName" `
            /o:"$orgName" `
            /d:sonar.token="$env:SONAR_TOKEN" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.cs.opencover.reportsPaths="**\TestResults\coverage.opencover.xml" # CRÍTICO: Aquí le decimos dónde buscar el informe
          
          # 2. Restaura y Compila (Mantenemos tu lógica)
          Write-Host "2. Restaurando y Compilando la solución..."
          dotnet restore $solutionPath
          dotnet build $solutionPath --configuration Release --no-restore
          
          # 3. EJECUTA TESTS Y GENERA INFORME DE COBERTURA
          # Debes tener al menos un proyecto de tests que Sonar pueda analizar (ej: "ReporteGasto.Tests.csproj")
          Write-Host "3. Ejecutando tests y generando informe de cobertura..."
          dotnet test $solutionPath `
            --no-build `
            --configuration Release `
            /p:CollectCoverage=true `
            /p:CoverletOutputFormat="opencover" `
            /p:CoverletOutput="./TestResults/coverage.opencover.xml" # CRÍTICO: Se guarda el informe aquí
            
          # 4. FINALIZA el análisis (SonarCloud lee el informe Coverlet que acabamos de generar)
          Write-Host "4. Finaliza el análisis de SonarScanner..."
          & $scanner end /d:sonar.token="$env:SONAR_TOKEN"
